/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type OrganizationProfile = {
  __typename: "OrganizationProfile",
  accessibilityFeatures?: string | null,
  buildingAge?: number | null,
  buildingType?: OrganizationProfileBuildingType | null,
  city?: string | null,
  country?: string | null,
  createdAt: string,
  emergencyContactEmail?: string | null,
  emergencyContactName?: string | null,
  emergencyContactPhone?: string | null,
  id: string,
  industry?: string | null,
  isOnboardingComplete?: boolean | null,
  lastUpdated?: string | null,
  nearestFireStation?: string | null,
  nearestHospital?: string | null,
  nearestPoliceStation?: string | null,
  numberOfFloors?: number | null,
  operatingHours?: string | null,
  organizationName: string,
  organizationType?: OrganizationProfileOrganizationType | null,
  owner?: string | null,
  primaryAddress?: string | null,
  primaryContactEmail?: string | null,
  primaryContactName?: string | null,
  primaryContactPhone?: string | null,
  primaryHazards?: string | null,
  secondaryContactEmail?: string | null,
  secondaryContactName?: string | null,
  secondaryContactPhone?: string | null,
  secondaryHazards?: string | null,
  specialConsiderations?: string | null,
  specialPopulations?: string | null,
  state?: string | null,
  totalOccupancy?: number | null,
  updatedAt: string,
  userId: string,
  zipCode?: string | null,
};

export enum OrganizationProfileBuildingType {
  Campus = "Campus",
  HighRise = "HighRise",
  Industrial = "Industrial",
  MultiStory = "MultiStory",
  Other = "Other",
  SingleStory = "SingleStory",
}


export enum OrganizationProfileOrganizationType {
  CorporateOffice = "CorporateOffice",
  EducationalInstitution = "EducationalInstitution",
  GovernmentBuilding = "GovernmentBuilding",
  HealthcareFacility = "HealthcareFacility",
  Manufacturing = "Manufacturing",
  Other = "Other",
  RetailCommercial = "RetailCommercial",
}


export type ModelOrganizationProfileFilterInput = {
  accessibilityFeatures?: ModelStringInput | null,
  and?: Array< ModelOrganizationProfileFilterInput | null > | null,
  buildingAge?: ModelIntInput | null,
  buildingType?: ModelOrganizationProfileBuildingTypeInput | null,
  city?: ModelStringInput | null,
  country?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  emergencyContactEmail?: ModelStringInput | null,
  emergencyContactName?: ModelStringInput | null,
  emergencyContactPhone?: ModelStringInput | null,
  id?: ModelIDInput | null,
  industry?: ModelStringInput | null,
  isOnboardingComplete?: ModelBooleanInput | null,
  lastUpdated?: ModelStringInput | null,
  nearestFireStation?: ModelStringInput | null,
  nearestHospital?: ModelStringInput | null,
  nearestPoliceStation?: ModelStringInput | null,
  not?: ModelOrganizationProfileFilterInput | null,
  numberOfFloors?: ModelIntInput | null,
  operatingHours?: ModelStringInput | null,
  or?: Array< ModelOrganizationProfileFilterInput | null > | null,
  organizationName?: ModelStringInput | null,
  organizationType?: ModelOrganizationProfileOrganizationTypeInput | null,
  owner?: ModelStringInput | null,
  primaryAddress?: ModelStringInput | null,
  primaryContactEmail?: ModelStringInput | null,
  primaryContactName?: ModelStringInput | null,
  primaryContactPhone?: ModelStringInput | null,
  primaryHazards?: ModelStringInput | null,
  secondaryContactEmail?: ModelStringInput | null,
  secondaryContactName?: ModelStringInput | null,
  secondaryContactPhone?: ModelStringInput | null,
  secondaryHazards?: ModelStringInput | null,
  specialConsiderations?: ModelStringInput | null,
  specialPopulations?: ModelStringInput | null,
  state?: ModelStringInput | null,
  totalOccupancy?: ModelIntInput | null,
  updatedAt?: ModelStringInput | null,
  userId?: ModelStringInput | null,
  zipCode?: ModelStringInput | null,
};

export type ModelStringInput = {
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  beginsWith?: string | null,
  between?: Array< string | null > | null,
  contains?: string | null,
  eq?: string | null,
  ge?: string | null,
  gt?: string | null,
  le?: string | null,
  lt?: string | null,
  ne?: string | null,
  notContains?: string | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  _null = "_null",
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
}


export type ModelSizeInput = {
  between?: Array< number | null > | null,
  eq?: number | null,
  ge?: number | null,
  gt?: number | null,
  le?: number | null,
  lt?: number | null,
  ne?: number | null,
};

export type ModelIntInput = {
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  between?: Array< number | null > | null,
  eq?: number | null,
  ge?: number | null,
  gt?: number | null,
  le?: number | null,
  lt?: number | null,
  ne?: number | null,
};

export type ModelOrganizationProfileBuildingTypeInput = {
  eq?: OrganizationProfileBuildingType | null,
  ne?: OrganizationProfileBuildingType | null,
};

export type ModelIDInput = {
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  beginsWith?: string | null,
  between?: Array< string | null > | null,
  contains?: string | null,
  eq?: string | null,
  ge?: string | null,
  gt?: string | null,
  le?: string | null,
  lt?: string | null,
  ne?: string | null,
  notContains?: string | null,
  size?: ModelSizeInput | null,
};

export type ModelBooleanInput = {
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  eq?: boolean | null,
  ne?: boolean | null,
};

export type ModelOrganizationProfileOrganizationTypeInput = {
  eq?: OrganizationProfileOrganizationType | null,
  ne?: OrganizationProfileOrganizationType | null,
};

export type ModelOrganizationProfileConnection = {
  __typename: "ModelOrganizationProfileConnection",
  items:  Array<OrganizationProfile | null >,
  nextToken?: string | null,
};

export type ModelOrganizationProfileConditionInput = {
  accessibilityFeatures?: ModelStringInput | null,
  and?: Array< ModelOrganizationProfileConditionInput | null > | null,
  buildingAge?: ModelIntInput | null,
  buildingType?: ModelOrganizationProfileBuildingTypeInput | null,
  city?: ModelStringInput | null,
  country?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  emergencyContactEmail?: ModelStringInput | null,
  emergencyContactName?: ModelStringInput | null,
  emergencyContactPhone?: ModelStringInput | null,
  industry?: ModelStringInput | null,
  isOnboardingComplete?: ModelBooleanInput | null,
  lastUpdated?: ModelStringInput | null,
  nearestFireStation?: ModelStringInput | null,
  nearestHospital?: ModelStringInput | null,
  nearestPoliceStation?: ModelStringInput | null,
  not?: ModelOrganizationProfileConditionInput | null,
  numberOfFloors?: ModelIntInput | null,
  operatingHours?: ModelStringInput | null,
  or?: Array< ModelOrganizationProfileConditionInput | null > | null,
  organizationName?: ModelStringInput | null,
  organizationType?: ModelOrganizationProfileOrganizationTypeInput | null,
  owner?: ModelStringInput | null,
  primaryAddress?: ModelStringInput | null,
  primaryContactEmail?: ModelStringInput | null,
  primaryContactName?: ModelStringInput | null,
  primaryContactPhone?: ModelStringInput | null,
  primaryHazards?: ModelStringInput | null,
  secondaryContactEmail?: ModelStringInput | null,
  secondaryContactName?: ModelStringInput | null,
  secondaryContactPhone?: ModelStringInput | null,
  secondaryHazards?: ModelStringInput | null,
  specialConsiderations?: ModelStringInput | null,
  specialPopulations?: ModelStringInput | null,
  state?: ModelStringInput | null,
  totalOccupancy?: ModelIntInput | null,
  updatedAt?: ModelStringInput | null,
  userId?: ModelStringInput | null,
  zipCode?: ModelStringInput | null,
};

export type CreateOrganizationProfileInput = {
  accessibilityFeatures?: string | null,
  buildingAge?: number | null,
  buildingType?: OrganizationProfileBuildingType | null,
  city?: string | null,
  country?: string | null,
  emergencyContactEmail?: string | null,
  emergencyContactName?: string | null,
  emergencyContactPhone?: string | null,
  id?: string | null,
  industry?: string | null,
  isOnboardingComplete?: boolean | null,
  lastUpdated?: string | null,
  nearestFireStation?: string | null,
  nearestHospital?: string | null,
  nearestPoliceStation?: string | null,
  numberOfFloors?: number | null,
  operatingHours?: string | null,
  organizationName: string,
  organizationType?: OrganizationProfileOrganizationType | null,
  primaryAddress?: string | null,
  primaryContactEmail?: string | null,
  primaryContactName?: string | null,
  primaryContactPhone?: string | null,
  primaryHazards?: string | null,
  secondaryContactEmail?: string | null,
  secondaryContactName?: string | null,
  secondaryContactPhone?: string | null,
  secondaryHazards?: string | null,
  specialConsiderations?: string | null,
  specialPopulations?: string | null,
  state?: string | null,
  totalOccupancy?: number | null,
  userId: string,
  zipCode?: string | null,
};

export type DeleteOrganizationProfileInput = {
  id: string,
};

export type UpdateOrganizationProfileInput = {
  accessibilityFeatures?: string | null,
  buildingAge?: number | null,
  buildingType?: OrganizationProfileBuildingType | null,
  city?: string | null,
  country?: string | null,
  emergencyContactEmail?: string | null,
  emergencyContactName?: string | null,
  emergencyContactPhone?: string | null,
  id: string,
  industry?: string | null,
  isOnboardingComplete?: boolean | null,
  lastUpdated?: string | null,
  nearestFireStation?: string | null,
  nearestHospital?: string | null,
  nearestPoliceStation?: string | null,
  numberOfFloors?: number | null,
  operatingHours?: string | null,
  organizationName?: string | null,
  organizationType?: OrganizationProfileOrganizationType | null,
  primaryAddress?: string | null,
  primaryContactEmail?: string | null,
  primaryContactName?: string | null,
  primaryContactPhone?: string | null,
  primaryHazards?: string | null,
  secondaryContactEmail?: string | null,
  secondaryContactName?: string | null,
  secondaryContactPhone?: string | null,
  secondaryHazards?: string | null,
  specialConsiderations?: string | null,
  specialPopulations?: string | null,
  state?: string | null,
  totalOccupancy?: number | null,
  userId?: string | null,
  zipCode?: string | null,
};

export type ModelSubscriptionOrganizationProfileFilterInput = {
  accessibilityFeatures?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionOrganizationProfileFilterInput | null > | null,
  buildingAge?: ModelSubscriptionIntInput | null,
  buildingType?: ModelSubscriptionStringInput | null,
  city?: ModelSubscriptionStringInput | null,
  country?: ModelSubscriptionStringInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  emergencyContactEmail?: ModelSubscriptionStringInput | null,
  emergencyContactName?: ModelSubscriptionStringInput | null,
  emergencyContactPhone?: ModelSubscriptionStringInput | null,
  id?: ModelSubscriptionIDInput | null,
  industry?: ModelSubscriptionStringInput | null,
  isOnboardingComplete?: ModelSubscriptionBooleanInput | null,
  lastUpdated?: ModelSubscriptionStringInput | null,
  nearestFireStation?: ModelSubscriptionStringInput | null,
  nearestHospital?: ModelSubscriptionStringInput | null,
  nearestPoliceStation?: ModelSubscriptionStringInput | null,
  numberOfFloors?: ModelSubscriptionIntInput | null,
  operatingHours?: ModelSubscriptionStringInput | null,
  or?: Array< ModelSubscriptionOrganizationProfileFilterInput | null > | null,
  organizationName?: ModelSubscriptionStringInput | null,
  organizationType?: ModelSubscriptionStringInput | null,
  owner?: ModelStringInput | null,
  primaryAddress?: ModelSubscriptionStringInput | null,
  primaryContactEmail?: ModelSubscriptionStringInput | null,
  primaryContactName?: ModelSubscriptionStringInput | null,
  primaryContactPhone?: ModelSubscriptionStringInput | null,
  primaryHazards?: ModelSubscriptionStringInput | null,
  secondaryContactEmail?: ModelSubscriptionStringInput | null,
  secondaryContactName?: ModelSubscriptionStringInput | null,
  secondaryContactPhone?: ModelSubscriptionStringInput | null,
  secondaryHazards?: ModelSubscriptionStringInput | null,
  specialConsiderations?: ModelSubscriptionStringInput | null,
  specialPopulations?: ModelSubscriptionStringInput | null,
  state?: ModelSubscriptionStringInput | null,
  totalOccupancy?: ModelSubscriptionIntInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
  userId?: ModelSubscriptionStringInput | null,
  zipCode?: ModelSubscriptionStringInput | null,
};

export type ModelSubscriptionStringInput = {
  beginsWith?: string | null,
  between?: Array< string | null > | null,
  contains?: string | null,
  eq?: string | null,
  ge?: string | null,
  gt?: string | null,
  in?: Array< string | null > | null,
  le?: string | null,
  lt?: string | null,
  ne?: string | null,
  notContains?: string | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionIntInput = {
  between?: Array< number | null > | null,
  eq?: number | null,
  ge?: number | null,
  gt?: number | null,
  in?: Array< number | null > | null,
  le?: number | null,
  lt?: number | null,
  ne?: number | null,
  notIn?: Array< number | null > | null,
};

export type ModelSubscriptionIDInput = {
  beginsWith?: string | null,
  between?: Array< string | null > | null,
  contains?: string | null,
  eq?: string | null,
  ge?: string | null,
  gt?: string | null,
  in?: Array< string | null > | null,
  le?: string | null,
  lt?: string | null,
  ne?: string | null,
  notContains?: string | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionBooleanInput = {
  eq?: boolean | null,
  ne?: boolean | null,
};

export type GetOrganizationProfileQueryVariables = {
  id: string,
};

export type GetOrganizationProfileQuery = {
  getOrganizationProfile?:  {
    __typename: "OrganizationProfile",
    accessibilityFeatures?: string | null,
    buildingAge?: number | null,
    buildingType?: OrganizationProfileBuildingType | null,
    city?: string | null,
    country?: string | null,
    createdAt: string,
    emergencyContactEmail?: string | null,
    emergencyContactName?: string | null,
    emergencyContactPhone?: string | null,
    id: string,
    industry?: string | null,
    isOnboardingComplete?: boolean | null,
    lastUpdated?: string | null,
    nearestFireStation?: string | null,
    nearestHospital?: string | null,
    nearestPoliceStation?: string | null,
    numberOfFloors?: number | null,
    operatingHours?: string | null,
    organizationName: string,
    organizationType?: OrganizationProfileOrganizationType | null,
    owner?: string | null,
    primaryAddress?: string | null,
    primaryContactEmail?: string | null,
    primaryContactName?: string | null,
    primaryContactPhone?: string | null,
    primaryHazards?: string | null,
    secondaryContactEmail?: string | null,
    secondaryContactName?: string | null,
    secondaryContactPhone?: string | null,
    secondaryHazards?: string | null,
    specialConsiderations?: string | null,
    specialPopulations?: string | null,
    state?: string | null,
    totalOccupancy?: number | null,
    updatedAt: string,
    userId: string,
    zipCode?: string | null,
  } | null,
};

export type ListOrganizationProfilesQueryVariables = {
  filter?: ModelOrganizationProfileFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListOrganizationProfilesQuery = {
  listOrganizationProfiles?:  {
    __typename: "ModelOrganizationProfileConnection",
    items:  Array< {
      __typename: "OrganizationProfile",
      accessibilityFeatures?: string | null,
      buildingAge?: number | null,
      buildingType?: OrganizationProfileBuildingType | null,
      city?: string | null,
      country?: string | null,
      createdAt: string,
      emergencyContactEmail?: string | null,
      emergencyContactName?: string | null,
      emergencyContactPhone?: string | null,
      id: string,
      industry?: string | null,
      isOnboardingComplete?: boolean | null,
      lastUpdated?: string | null,
      nearestFireStation?: string | null,
      nearestHospital?: string | null,
      nearestPoliceStation?: string | null,
      numberOfFloors?: number | null,
      operatingHours?: string | null,
      organizationName: string,
      organizationType?: OrganizationProfileOrganizationType | null,
      owner?: string | null,
      primaryAddress?: string | null,
      primaryContactEmail?: string | null,
      primaryContactName?: string | null,
      primaryContactPhone?: string | null,
      primaryHazards?: string | null,
      secondaryContactEmail?: string | null,
      secondaryContactName?: string | null,
      secondaryContactPhone?: string | null,
      secondaryHazards?: string | null,
      specialConsiderations?: string | null,
      specialPopulations?: string | null,
      state?: string | null,
      totalOccupancy?: number | null,
      updatedAt: string,
      userId: string,
      zipCode?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type CreateOrganizationProfileMutationVariables = {
  condition?: ModelOrganizationProfileConditionInput | null,
  input: CreateOrganizationProfileInput,
};

export type CreateOrganizationProfileMutation = {
  createOrganizationProfile?:  {
    __typename: "OrganizationProfile",
    accessibilityFeatures?: string | null,
    buildingAge?: number | null,
    buildingType?: OrganizationProfileBuildingType | null,
    city?: string | null,
    country?: string | null,
    createdAt: string,
    emergencyContactEmail?: string | null,
    emergencyContactName?: string | null,
    emergencyContactPhone?: string | null,
    id: string,
    industry?: string | null,
    isOnboardingComplete?: boolean | null,
    lastUpdated?: string | null,
    nearestFireStation?: string | null,
    nearestHospital?: string | null,
    nearestPoliceStation?: string | null,
    numberOfFloors?: number | null,
    operatingHours?: string | null,
    organizationName: string,
    organizationType?: OrganizationProfileOrganizationType | null,
    owner?: string | null,
    primaryAddress?: string | null,
    primaryContactEmail?: string | null,
    primaryContactName?: string | null,
    primaryContactPhone?: string | null,
    primaryHazards?: string | null,
    secondaryContactEmail?: string | null,
    secondaryContactName?: string | null,
    secondaryContactPhone?: string | null,
    secondaryHazards?: string | null,
    specialConsiderations?: string | null,
    specialPopulations?: string | null,
    state?: string | null,
    totalOccupancy?: number | null,
    updatedAt: string,
    userId: string,
    zipCode?: string | null,
  } | null,
};

export type DeleteOrganizationProfileMutationVariables = {
  condition?: ModelOrganizationProfileConditionInput | null,
  input: DeleteOrganizationProfileInput,
};

export type DeleteOrganizationProfileMutation = {
  deleteOrganizationProfile?:  {
    __typename: "OrganizationProfile",
    accessibilityFeatures?: string | null,
    buildingAge?: number | null,
    buildingType?: OrganizationProfileBuildingType | null,
    city?: string | null,
    country?: string | null,
    createdAt: string,
    emergencyContactEmail?: string | null,
    emergencyContactName?: string | null,
    emergencyContactPhone?: string | null,
    id: string,
    industry?: string | null,
    isOnboardingComplete?: boolean | null,
    lastUpdated?: string | null,
    nearestFireStation?: string | null,
    nearestHospital?: string | null,
    nearestPoliceStation?: string | null,
    numberOfFloors?: number | null,
    operatingHours?: string | null,
    organizationName: string,
    organizationType?: OrganizationProfileOrganizationType | null,
    owner?: string | null,
    primaryAddress?: string | null,
    primaryContactEmail?: string | null,
    primaryContactName?: string | null,
    primaryContactPhone?: string | null,
    primaryHazards?: string | null,
    secondaryContactEmail?: string | null,
    secondaryContactName?: string | null,
    secondaryContactPhone?: string | null,
    secondaryHazards?: string | null,
    specialConsiderations?: string | null,
    specialPopulations?: string | null,
    state?: string | null,
    totalOccupancy?: number | null,
    updatedAt: string,
    userId: string,
    zipCode?: string | null,
  } | null,
};

export type UpdateOrganizationProfileMutationVariables = {
  condition?: ModelOrganizationProfileConditionInput | null,
  input: UpdateOrganizationProfileInput,
};

export type UpdateOrganizationProfileMutation = {
  updateOrganizationProfile?:  {
    __typename: "OrganizationProfile",
    accessibilityFeatures?: string | null,
    buildingAge?: number | null,
    buildingType?: OrganizationProfileBuildingType | null,
    city?: string | null,
    country?: string | null,
    createdAt: string,
    emergencyContactEmail?: string | null,
    emergencyContactName?: string | null,
    emergencyContactPhone?: string | null,
    id: string,
    industry?: string | null,
    isOnboardingComplete?: boolean | null,
    lastUpdated?: string | null,
    nearestFireStation?: string | null,
    nearestHospital?: string | null,
    nearestPoliceStation?: string | null,
    numberOfFloors?: number | null,
    operatingHours?: string | null,
    organizationName: string,
    organizationType?: OrganizationProfileOrganizationType | null,
    owner?: string | null,
    primaryAddress?: string | null,
    primaryContactEmail?: string | null,
    primaryContactName?: string | null,
    primaryContactPhone?: string | null,
    primaryHazards?: string | null,
    secondaryContactEmail?: string | null,
    secondaryContactName?: string | null,
    secondaryContactPhone?: string | null,
    secondaryHazards?: string | null,
    specialConsiderations?: string | null,
    specialPopulations?: string | null,
    state?: string | null,
    totalOccupancy?: number | null,
    updatedAt: string,
    userId: string,
    zipCode?: string | null,
  } | null,
};

export type OnCreateOrganizationProfileSubscriptionVariables = {
  filter?: ModelSubscriptionOrganizationProfileFilterInput | null,
  owner?: string | null,
};

export type OnCreateOrganizationProfileSubscription = {
  onCreateOrganizationProfile?:  {
    __typename: "OrganizationProfile",
    accessibilityFeatures?: string | null,
    buildingAge?: number | null,
    buildingType?: OrganizationProfileBuildingType | null,
    city?: string | null,
    country?: string | null,
    createdAt: string,
    emergencyContactEmail?: string | null,
    emergencyContactName?: string | null,
    emergencyContactPhone?: string | null,
    id: string,
    industry?: string | null,
    isOnboardingComplete?: boolean | null,
    lastUpdated?: string | null,
    nearestFireStation?: string | null,
    nearestHospital?: string | null,
    nearestPoliceStation?: string | null,
    numberOfFloors?: number | null,
    operatingHours?: string | null,
    organizationName: string,
    organizationType?: OrganizationProfileOrganizationType | null,
    owner?: string | null,
    primaryAddress?: string | null,
    primaryContactEmail?: string | null,
    primaryContactName?: string | null,
    primaryContactPhone?: string | null,
    primaryHazards?: string | null,
    secondaryContactEmail?: string | null,
    secondaryContactName?: string | null,
    secondaryContactPhone?: string | null,
    secondaryHazards?: string | null,
    specialConsiderations?: string | null,
    specialPopulations?: string | null,
    state?: string | null,
    totalOccupancy?: number | null,
    updatedAt: string,
    userId: string,
    zipCode?: string | null,
  } | null,
};

export type OnDeleteOrganizationProfileSubscriptionVariables = {
  filter?: ModelSubscriptionOrganizationProfileFilterInput | null,
  owner?: string | null,
};

export type OnDeleteOrganizationProfileSubscription = {
  onDeleteOrganizationProfile?:  {
    __typename: "OrganizationProfile",
    accessibilityFeatures?: string | null,
    buildingAge?: number | null,
    buildingType?: OrganizationProfileBuildingType | null,
    city?: string | null,
    country?: string | null,
    createdAt: string,
    emergencyContactEmail?: string | null,
    emergencyContactName?: string | null,
    emergencyContactPhone?: string | null,
    id: string,
    industry?: string | null,
    isOnboardingComplete?: boolean | null,
    lastUpdated?: string | null,
    nearestFireStation?: string | null,
    nearestHospital?: string | null,
    nearestPoliceStation?: string | null,
    numberOfFloors?: number | null,
    operatingHours?: string | null,
    organizationName: string,
    organizationType?: OrganizationProfileOrganizationType | null,
    owner?: string | null,
    primaryAddress?: string | null,
    primaryContactEmail?: string | null,
    primaryContactName?: string | null,
    primaryContactPhone?: string | null,
    primaryHazards?: string | null,
    secondaryContactEmail?: string | null,
    secondaryContactName?: string | null,
    secondaryContactPhone?: string | null,
    secondaryHazards?: string | null,
    specialConsiderations?: string | null,
    specialPopulations?: string | null,
    state?: string | null,
    totalOccupancy?: number | null,
    updatedAt: string,
    userId: string,
    zipCode?: string | null,
  } | null,
};

export type OnUpdateOrganizationProfileSubscriptionVariables = {
  filter?: ModelSubscriptionOrganizationProfileFilterInput | null,
  owner?: string | null,
};

export type OnUpdateOrganizationProfileSubscription = {
  onUpdateOrganizationProfile?:  {
    __typename: "OrganizationProfile",
    accessibilityFeatures?: string | null,
    buildingAge?: number | null,
    buildingType?: OrganizationProfileBuildingType | null,
    city?: string | null,
    country?: string | null,
    createdAt: string,
    emergencyContactEmail?: string | null,
    emergencyContactName?: string | null,
    emergencyContactPhone?: string | null,
    id: string,
    industry?: string | null,
    isOnboardingComplete?: boolean | null,
    lastUpdated?: string | null,
    nearestFireStation?: string | null,
    nearestHospital?: string | null,
    nearestPoliceStation?: string | null,
    numberOfFloors?: number | null,
    operatingHours?: string | null,
    organizationName: string,
    organizationType?: OrganizationProfileOrganizationType | null,
    owner?: string | null,
    primaryAddress?: string | null,
    primaryContactEmail?: string | null,
    primaryContactName?: string | null,
    primaryContactPhone?: string | null,
    primaryHazards?: string | null,
    secondaryContactEmail?: string | null,
    secondaryContactName?: string | null,
    secondaryContactPhone?: string | null,
    secondaryHazards?: string | null,
    specialConsiderations?: string | null,
    specialPopulations?: string | null,
    state?: string | null,
    totalOccupancy?: number | null,
    updatedAt: string,
    userId: string,
    zipCode?: string | null,
  } | null,
};
